site_name: The Kitsune Project
site_url: "https://thekitsuneproject.com/"

extra_css:
  - stylesheets/extra.css

theme:
  favicon: assets/img/favicon_fox.ico
  logo: assets/img/fox-origami-paper-orange.svg
  features:
    - search.suggest
    - search.highlight
    - navigation.sections
    - navigation.expand
    - navigation.instant

  name: material
  custom_footer:
    enabled: false

  language: 'es'
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  extra_css:
   - stylesheets/extra.css
  


nav:
  - 'Inicio': 'index.md'
  - 'MEXT':
      - 'Beca Monbukagakusho (MEXT)': 'mext/intro.md'
      - 'Inglés': 'mext/english.md'
      - 'Matemáticas': 'mext/matematicas.md'
  - 'Japonés':
      - 'JLPT':
          - 'Nivel N4': 'jlpt/jlpt-n4.md'
        
  - 'Recursos': 'recursos.md'
  - 'Acerca de': 'about.md'
  
  
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences


plugins:
  - search:
      lang: es



